# Home work 1st module

In [3]:
#Importing the first libraries that we´re going to use
import pandas as pd
import numpy as np

In [4]:
#Checking the version of pandas

pd.__version__

'2.3.3'

In [1]:
#Reading the datra that we´re going to use

data = 'https://raw.githubusercontent.com/Javier-Gutierrez/machine-learning-zoomcamp/refs/heads/main/cohorts/2026/data/car_fuel_efficiency_2026.csv'

In [5]:
#Transforming on a DataFrame

df = pd.read_csv(data)

In [6]:
#Getting the info of the dataset

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  object
 2   fuel_type            10000 non-null  object
 3   drivetrain           10000 non-null  object
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), object(3)
memory usage: 859.5+ KB
None

In [7]:
#Searching for fuel types
print(df.nunique())

model_year              50
origin                   3
fuel_type                3
drivetrain               3
num_doors                4
engine_displacement    127
num_cylinders            5
horsepower             153
vehicle_weight         176
acceleration            93
fuel_efficiency_mpg    188
dtype: int64

In [8]:
#Searching for columns that have null values

print(df.isnull().sum())

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [9]:
#Searching for max fuel efficiency value

print(df.groupby('origin').max())

        model_year fuel_type        drivetrain  num_doors  \
origin
Asia          2024    Hybrid  Rear-wheel drive          5
Europe        2024    Hybrid  Rear-wheel drive          5
USA           2024    Hybrid  Rear-wheel drive          5

        engine_displacement  num_cylinders  horsepower  vehicle_weight  \
origin
Asia                   3020              8       334.0            5280
Europe                 2870              8       332.0            5040
USA                    3110              8       334.0            5460

        acceleration  fuel_efficiency_mpg
origin
Asia            23.8                 41.2
Europe          23.4                 39.4
USA             22.8                 38.2

In [10]:
#Q6 1.- Median
print(df['horsepower'].mean())

254.44601556505535

In [11]:
#Q6 2.- Calculate the most frecuent value at housepower column

print(df['horsepower'].value_counts().index[0])

252.0

In [12]:
#Q6 3.- Filling NA values

df['horsepower'] = df['horsepower'].fillna(252)
print(df['horsepower'].value_counts())

horsepower
252.0    1051
246.0     168
256.0     168
259.0     165
253.0     165
         ...
322.0       1
330.0       1
175.0       1
178.0       1
320.0       1
Name: count, Length: 153, dtype: int64

In [13]:
#Q6 4.- Calc mean again

print(df['horsepower'].mean())

254.2315

In [14]:
#Q7 1.- Cars from ASIA

df_Asia = df[df['origin'] == 'Asia']

df_Asia

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [15]:
#Q7 2.- Filtering by weight and model year
df_Asia_WY = df_Asia[['vehicle_weight','model_year']]
df_Asia_WY

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [19]:
#Q7 3.- Selecting the first 7 val
df_7_values=df_Asia_WY.head(7)
df_7_values

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [40]:
#Q7 4.-Get the underlying NmPy array. X
X=np.array(df_7_values)
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [41]:
#Q7 5.- Matrix multiplication with X transpose

XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [42]:
#Q7 6.- Getting XTX inverted
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [ ]:
#Checking for the identity matrix
XTX.dot(XTX_inv).round(1)

array([[ 1., -0.],
       [-0.,  1.]])

In [38]:
#Q7 7.-Creating y values

y = np.array([1100,1300,800,900,1000,1100,1200],)
y.shape

(7,)

In [43]:
#Q7 8.- Multiplying XTX_INV dot XTX dot y

w = XTX_inv.dot(X.T).dot(y)
w

array([0.13644777, 0.2327492 ])

In [46]:
#Q7 9. Sum of weights

w.sum()

np.float64(0.36919696904925486)